const express = require('express')
const morgan = require('morgan')
const path = require('path')
const app = express()
const router = require('../routes/routes.js')
app.use(express.json())
app.use(morgan('dev'))
app.use('/files', express.static(path.resolve(__dirname, '../public', 'upload')))
app.use(router)
module.exports = app
